=== MarvelousMartin/culs-markup-language/Exercise 4/summary.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="cenaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="mena"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="pocetAkciiType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="vlastnik"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="akcieType">
    <xs:sequence>
      <xs:element type="xs:string" name="nazev"/>
      <xs:element type="cenaType" name="cena"/>
      <xs:element type="pocetAkciiType" name="pocetAkcii" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cennePapiryType">
    <xs:sequence>
      <xs:element type="akcieType" name="akcie"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="kryptomenaType">
    <xs:sequence>
      <xs:element name="nazev">
      </xs:element>
      <xs:element name="zkratka">
        <xs:simpleType>
          <!-- Maximalne 4 uppercase znaky-->
          <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z][A-Z][A-Z]"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="vObehuOd">
        <xs:simpleType>
          <!-- Prvni kryptomena vznikla 2013 (BTC) -->
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="2013"/>
            <xs:maxInclusive value="2021"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="zalozil">
        <xs:simpleType>
          <!-- Soucet pismen ve jmene a prijmeni max 30 -->
          <xs:restriction base="xs:string">
            <xs:maxLength value="30"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pocetMinci">
      </xs:element>
      <xs:element type="cenaType" name="cena" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="halvingNext">
        <xs:simpleType>
          <!-- Pristi halving nemuze byt drive nez letos -->
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="2021"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="kryptoType">
    <xs:sequence>
      <xs:element type="kryptomenaType" name="kryptomena" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="koupeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="mena">
          <xs:simpleType>
            <!-- CryptoPunks jdou koupit pouze pres ETH blockchain -->
            <xs:restriction base="xs:integer">
              <xs:enumeration value="ETH"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="vlastnostType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="nazev"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="vlastnostiType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="vlastnostType" name="vlastnost"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="tokenType">
    <xs:sequence>
      <xs:element type="xs:string" name="nazev"/>
      <xs:element type="koupeType" name="koupe"/>
      <xs:element type="vlastnostiType" name="vlastnosti"/>
    </xs:sequence>
    <xs:attribute name="typ">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <!-- NFT tokeny jsou akceptovatelné -->
          <xs:enumeration value="NFT"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="tokenyType">
    <xs:sequence>
      <xs:element type="tokenType" name="token"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="trhType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="druh"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="komoditaType">
    <xs:sequence>
      <xs:element name="nazev">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Pouze zlato, stříbro a ropa -->
            <xs:enumeration value="Zlato"/>
            <xs:enumeration value="Stříbro"/>
            <xs:enumeration value="Ropa"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="cenaType" name="cena"/>
      <xs:element name="trh">
        <xs:simpleType>
          <!-- Jiné trhy nez býčí a medvědí neexistují -->
          <xs:restriction base="xs:string">
            <xs:enumeration value="Bullish|Bearish"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="kod">
      <xs:simpleType>
        <!-- Každá komodita začíná písmenem X -->
        <xs:restriction base="xs:string">
          <xs:enumeration value="[X]*"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="komodityType">
    <xs:sequence>
      <xs:element type="komoditaType" name="komodita" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="portfolioType">
    <xs:sequence>
      <xs:element type="cennePapiryType" name="cennePapiry"/>
      <xs:element type="kryptoType" name="krypto"/>
      <xs:element type="tokenyType" name="tokeny"/>
      <xs:element type="komodityType" name="komodity"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="portfolioType" name="portfolio"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== MarvelousMartin/culs-markup-language/Exercise 4/summary.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xslt" href="/summary.xslt"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summary.xsd">
    <portfolio>
        <cennePapiry>
            <akcie>
                <nazev>Tesla</nazev>
                <cena mena="USD">652.1</cena>
                <akcionari>
                    <pocetAkcii vlastnik="Martin">0.35</pocetAkcii>
                </akcionari>
            </akcie>
        </cennePapiry>
        <krypto>
            <kryptomena>
                <nazev>Bitcoin</nazev>
                <zkratka>BTC</zkratka>
                <vObehuOd>2009</vObehuOd>
                <zalozil>Satoshi Nakamoto</zalozil>
                <pocetMinci>21000000</pocetMinci>
                <cena mena="USD">58450</cena>
                <halvingNext>2024</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Ethereum</nazev>
                <zkratka>ETH</zkratka>
                <vObehuOd>2014</vObehuOd>
                <zalozil>Joe Lubin</zalozil>
                <pocetMinci>inf</pocetMinci>
                <cena mena="USD">1860</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Litecoin</nazev>
                <zkratka>LTC</zkratka>
                <vObehuOd>2013</vObehuOd>
                <zalozil>Charlie Lee</zalozil>
                <pocetMinci>84000000</pocetMinci>
                <cena mena="USD">204</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Ripple</nazev>
                <zkratka>XRP</zkratka>
                <vObehuOd>2012</vObehuOd>
                <zalozil>Chris Larsen</zalozil>
                <pocetMinci>100000000000</pocetMinci>
                <cena mena="USD">0.48</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>RavenCoin</nazev>
                <zkratka>RVN</zkratka>
                <vObehuOd>2011</vObehuOd>
                <zalozil>Ted Kim</zalozil>
                <pocetMinci>21000000000</pocetMinci>
                <cena mena="USD">0.21</cena>
                <halvingNext>2022</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Stellar</nazev>
                <zkratka>XLM</zkratka>
                <vObehuOd>2014</vObehuOd>
                <zalozil>Jed McCaleb</zalozil>
                <pocetMinci>50000000000</pocetMinci>
                <cena mena="USD">0.4</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Polkadot</nazev>
                <zkratka>DOT</zkratka>
                <vObehuOd>2020</vObehuOd>
                <zalozil>Gavin Wood</zalozil>
                <pocetMinci>1057896407</pocetMinci>
                <cena mena="USD">40</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Dogecoin</nazev>
                <zkratka>DOGE</zkratka>
                <vObehuOd>2013</vObehuOd>
                <zalozil>Billy Markus</zalozil>
                <pocetMinci>inf</pocetMinci>
                <cena mena="USD">0.05</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Monero</nazev>
                <zkratka>XMR</zkratka>
                <vObehuOd>2014</vObehuOd>
                <zalozil>Nicolas van Saberhagen</zalozil>
                <pocetMinci>inf</pocetMinci>
                <cena mena="USD">234</cena>
                <halvingNext>2021</halvingNext>
            </kryptomena>
            <kryptomena>
                <nazev>Binance Coin</nazev>
                <zkratka>BNB</zkratka>
                <vObehuOd>2017</vObehuOd>
                <zalozil>Brian Chesky</zalozil>
                <pocetMinci>170533651</pocetMinci>
                <cena mena="USD">271</cena>
                <halvingNext>NaN</halvingNext>
            </kryptomena>
        </krypto>
        <tokeny>
            <token typ="NFT">
                <nazev>Cryptopunk #5563</nazev>
                <koupe mena="ETH">1.02</koupe>
                <vlastnosti>
                    <vlastnost nazev="Vape">
                        <pocet>272</pocet>
                    </vlastnost>
                    <vlastnost nazev="Hot Lipstick">
                        <pocet>696</pocet>
                    </vlastnost>
                    <vlastnost nazev="Wild Blonde">
                        <pocet>144</pocet>
                    </vlastnost>
                    <vlastnost nazev="Earring">
                        <pocet>2459</pocet>
                    </vlastnost>
                </vlastnosti>
            </token>
        </tokeny>
        <komodity>
            <komodita>
                <kod>XAU</kod>
                <nazev>Zlato</nazev>
                <cena mena="CZK">38173.86</cena>
                <trh>Bearish</trh>
            </komodita>
            <komodita>
                <kod>XAG</kod>
                <nazev>Stříbro</nazev>
                <cena mena="CZK">573.69</cena>
                <trh>Bullish</trh>
            </komodita>
        </komodity>
    </portfolio>
</root>
